version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: noteplane
      POSTGRES_PASSWORD: password
      POSTGRES_DB: noteplane
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
