version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  pgdata:
